
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                S_Id = 1F,
                S_Name = @"Patel Yarmi",
                Sem = 3F,
                IT = 8.2F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual AGRI with predicted AGRI from sample data...\n\n");


            Console.WriteLine($"S_Id: {1F}");
            Console.WriteLine($"S_Name: {@"Patel Yarmi"}");
            Console.WriteLine($"Sem: {3F}");
            Console.WriteLine($"IT: {8.2F}");
            Console.WriteLine($"AGRI: {7.5F}");


            Console.WriteLine($"\n\nPredicted AGRI: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
